// <auto-generated />
using System;
using DataBaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataBaseContext.Migrations
{
    [DbContext(typeof(AplikacijaDbContext))]
    partial class AplikacijaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("DatabaseEntityLib.Models.Aktivnost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlaniraniSati")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ZadatakId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ZadatakId");

                    b.ToTable("Aktivnosti");
                });

            modelBuilder.Entity("DatabaseEntityLib.Models.ClanTima", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumPridruzivanja")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uloga")
                        .HasColumnType("TEXT");

                    b.Property<int>("ZaposleniId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TimId");

                    b.HasIndex("ZaposleniId");

                    b.ToTable("ClanoviTimova");
                });

            modelBuilder.Entity("DatabaseEntityLib.Models.DodelaZadatka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AktivnostId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ZaposleniId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AktivnostId");

                    b.HasIndex("ZaposleniId");

                    b.ToTable("DodeleZadataka");
                });

            modelBuilder.Entity("DatabaseEntityLib.Models.Projekat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumPocetka")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumZavrsetka")
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlaniraniSati")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Projekti");
                });

            modelBuilder.Entity("DatabaseEntityLib.Models.RadniPaket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlaniraniSati")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProjekatId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjekatId");

                    b.ToTable("RadniPaketi");
                });

            modelBuilder.Entity("DatabaseEntityLib.Models.Tim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjekatId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjekatId");

                    b.ToTable("Timovi");
                });

            modelBuilder.Entity("DatabaseEntityLib.Models.Zadatak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlaniraniSati")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RadniPaketId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RadniPaketId");

                    b.ToTable("Zadaci");
                });

            modelBuilder.Entity("DatabaseEntityLib.Models.Zaposleni", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pozicija")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Zaposleni");
                });

            modelBuilder.Entity("DatabaseEntityLib.Models.Aktivnost", b =>
                {
                    b.HasOne("DatabaseEntityLib.Models.Zadatak", "Zadatak")
                        .WithMany("Aktivnosti")
                        .HasForeignKey("ZadatakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zadatak");
                });

            modelBuilder.Entity("DatabaseEntityLib.Models.ClanTima", b =>
                {
                    b.HasOne("DatabaseEntityLib.Models.Tim", "Tim")
                        .WithMany("Clanovi")
                        .HasForeignKey("TimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseEntityLib.Models.Zaposleni", "Zaposleni")
                        .WithMany("Clanstva")
                        .HasForeignKey("ZaposleniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tim");

                    b.Navigation("Zaposleni");
                });

            modelBuilder.Entity("DatabaseEntityLib.Models.DodelaZadatka", b =>
                {
                    b.HasOne("DatabaseEntityLib.Models.Aktivnost", "Aktivnost")
                        .WithMany("Dodele")
                        .HasForeignKey("AktivnostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseEntityLib.Models.Zaposleni", "Zaposleni")
                        .WithMany("Dodele")
                        .HasForeignKey("ZaposleniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aktivnost");

                    b.Navigation("Zaposleni");
                });

            modelBuilder.Entity("DatabaseEntityLib.Models.RadniPaket", b =>
                {
                    b.HasOne("DatabaseEntityLib.Models.Projekat", "Projekat")
                        .WithMany("RadniPaketi")
                        .HasForeignKey("ProjekatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projekat");
                });

            modelBuilder.Entity("DatabaseEntityLib.Models.Tim", b =>
                {
                    b.HasOne("DatabaseEntityLib.Models.Projekat", "Projekat")
                        .WithMany("Timovi")
                        .HasForeignKey("ProjekatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projekat");
                });

            modelBuilder.Entity("DatabaseEntityLib.Models.Zadatak", b =>
                {
                    b.HasOne("DatabaseEntityLib.Models.RadniPaket", "RadniPaket")
                        .WithMany("Zadatci")
                        .HasForeignKey("RadniPaketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RadniPaket");
                });

            modelBuilder.Entity("DatabaseEntityLib.Models.Aktivnost", b =>
                {
                    b.Navigation("Dodele");
                });

            modelBuilder.Entity("DatabaseEntityLib.Models.Projekat", b =>
                {
                    b.Navigation("RadniPaketi");

                    b.Navigation("Timovi");
                });

            modelBuilder.Entity("DatabaseEntityLib.Models.RadniPaket", b =>
                {
                    b.Navigation("Zadatci");
                });

            modelBuilder.Entity("DatabaseEntityLib.Models.Tim", b =>
                {
                    b.Navigation("Clanovi");
                });

            modelBuilder.Entity("DatabaseEntityLib.Models.Zadatak", b =>
                {
                    b.Navigation("Aktivnosti");
                });

            modelBuilder.Entity("DatabaseEntityLib.Models.Zaposleni", b =>
                {
                    b.Navigation("Clanstva");

                    b.Navigation("Dodele");
                });
#pragma warning restore 612, 618
        }
    }
}
